version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"
    ports:
        - 1433:1433

  db2:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"
    ports:
        - 1432:1433

  db3:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"
    ports:
        - 1431:1433

  tartak.webapp.server:
    image: ${DOCKER_REGISTRY-}tartakwebappserver
    restart: always
    build:
      context: .
      dockerfile: Tartak.WebApp/Server/Dockerfile
    ports:
        - 5001:443
    depends_on:
        - db

  tartak.sklep:
    image: ${DOCKER_REGISTRY-}tartaksklep
    restart: always
    build:
      context: .
      dockerfile: Tartak.Sklep/Dockerfile
    depends_on:
        - db2


  tartak.magazyn:
    image: ${DOCKER_REGISTRY-}tartakmagazyn
    restart: always
    build:
      context: .
      dockerfile: Tartak.Magazyn/Dockerfile
    depends_on:
        - db3

networks:
  default:
    name: network-aa

